In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [27]:
df = pd.read_csv("raid_test_5000.csv")

In [28]:
df.head(10)

,Unnamed: 0.1,Unnamed: 0,id,adv_source_id,source_id,model,decoding,repetition_penalty,attack,domain,title,prompt,generation
0,1698258,1698258,fc5c4cbb-ec61-492f-8973-0ed504022dc1,6fb2fad1-9165-433f-ac4f-41c41ef99595,6fb2fad1-9165-433f-ac4f-41c41ef99595,human,NaN,NaN,article_deletion,news,Mixed reaction to Man Utd offer,NaN,Shares in Manchester United were up over 5% by...
1,946266,946266,abb69637-74f2-45f5-97a8-56397d1da160,b6b6a49a-b329-4535-8602-c9cddc672cd6,b6b6a49a-b329-4535-8602-c9cddc672cd6,human,NaN,NaN,homoglyph,books,The Infernal Desire Machines of Doctor Hoffman,NaN,Тhе nоvеl рrеsеnts thе stоrу frоm thе реrsрес...
2,3468714,3468714,0bcf1ddc-081b-4bb1-a877-e342ace96ae6,5ff0d295-e31a-4cd1-99ed-bdf91a9659af,09824ae0-e100-4d68-aeec-8bf4edfaeb79,llama-chat,greedy,yes,insert_paragraphs,recipes,Bacon And Butternut Pasta,"Write a recipe for ""Bacon And Butternut Pasta"".",Sure! \n\nHere's a simple recipe for Bacon and...
3,3873106,3873106,934e8454-9189-47eb-ab9c-10f1786f7e95,0cd8bfc8-37f2-4104-8629-1db2bd78c3ae,cf63e7a3-5d0a-4636-8c79-97cf4733caa0,mpt-chat,greedy,no,number,reddit,Germinating / sowing seeds,"Write just the body of a Reddit post titled ""G...",Hey everyone! I'm really excited to start germ...
4,5007651,5007651,aee95636-f52f-4e45-8e73-a75503f783fd,2f7f644e-6b98-45fe-bf67-b31a4ad0b37c,2f7f644e-6b98-45fe-bf67-b31a4ad0b37c,human,NaN,NaN,number,wiki,Richard Payne Knight,NaN,Richard Payne Knight (11 February 1751 – 85 Ap...
5,284894,284894,c6f07833-7a86-4412-b3d4-67948d2f34b2,c6f07833-7a86-4412-b3d4-67948d2f34b2,064f466c-9fd4-442b-9f0d-105eb023214f,mpt,greedy,yes,none,abstracts,Solving the Crystallographic Phase Problem usi...,The following is the full text of the abstract...,We present an algorithm to solve crystallograp...
6,3027338,3027338,5adf25dd-8991-4ccc-9ad2-eda3978430a7,1fd84a57-e37d-4d02-b204-7d4897b1b83b,1fd84a57-e37d-4d02-b204-7d4897b1b83b,human,NaN,NaN,upper_lower,recipes,Goat Cheese and Rosemary Tart with Shaved Pros...,NaN,1/2 cup honey\n1/2 Cup Armagnac\n8 to 12 large...
7,4927971,4927971,568c0af7-9e31-49c1-a7ab-1c3effe9629b,a23de928-8e40-4cb1-a9b1-7fd2c922b157,a23de928-8e40-4cb1-a9b1-7fd2c922b157,human,NaN,NaN,upper_lower,wiki,"Prestonsburg, Kentucky",NaN,Prestonsburg is a small home rule-class city i...
8,1221868,1221868,73a099a9-62dd-4fa7-980b-039e9e2e235d,29facb32-5090-470c-9ce6-cff78827d60d,91fc0465-dac4-405a-bb3a-db5ac19c0d2d,gpt3,sampling,no,number,books,House Rules,The following is the full text of a plot summa...,\n\nCaleb is a young man with Asperger's Syndr...
9,3260631,3260631,47562cbb-3686-4bd1-b280-2047a0a8f915,47562cbb-3686-4bd1-b280-2047a0a8f915,89652175-9752-4896-9c9d-5cd3038452e2,chatgpt,sampling,no,none,recipes,Bobby Flays Yucatan Chicken Puffy Tacos with P...,"Write a recipe for ""Bobby Flays Yucatan Chicke...",Yucatan Chicken Puffy Tacos with Peanut Red Ch...

In [29]:
y = df.pop('model')
y.head(10)

0         human
1         human
2    llama-chat
3      mpt-chat
4         human
5           mpt
6         human
7         human
8          gpt3
9       chatgpt
Name: model, dtype: object

In [30]:
X = df[['generation', 'attack', 'domain', 'repetition_penalty']]
X.head(10)

,generation,attack,domain,repetition_penalty
0,Shares in Manchester United were up over 5% by...,article_deletion,news,NaN
1,Тhе nоvеl рrеsеnts thе stоrу frоm thе реrsрес...,homoglyph,books,NaN
2,Sure! \n\nHere's a simple recipe for Bacon and...,insert_paragraphs,recipes,yes
3,Hey everyone! I'm really excited to start germ...,number,reddit,no
4,Richard Payne Knight (11 February 1751 – 85 Ap...,number,wiki,NaN
5,We present an algorithm to solve crystallograp...,none,abstracts,yes
6,1/2 cup honey\n1/2 Cup Armagnac\n8 to 12 large...,upper_lower,recipes,NaN
7,Prestonsburg is a small home rule-class city i...,upper_lower,wiki,NaN
8,\n\nCaleb is a young man with Asperger's Syndr...,number,books,no
9,Yucatan Chicken Puffy Tacos with Peanut Red Ch...,none,recipes,no

In [31]:
X_big, X_small, y_big, y_small = train_test_split( X, y, test_size=100, random_state=42, stratify=y)

In [36]:
print(X_small.shape, y_small.shape)

(100, 4) (100,)

In [52]:
X_small.head()

,generation,attack,domain,repetition_penalty
1516,Segmentations-Leak: Membership Inference Attac...,perplexity_misspelling,abstracts,no
2064,"Farshid Jamshidian is a finance researcher, ac...",insert_paragraphs,wiki,NaN
999,Transient spine enlargement (3-5 min timesca...,alternative_spelling,abstracts,NaN
644,The viola da Terceira (also viola Terceiren...,whitespace,wiki,NaN
3721,Yes this review is 2 years after the film's re...,insert_paragraphs,reviews,NaN

In [50]:
y_small.head()

1516    mistral-chat
2064           human
999            human
644            human
3721           human
Name: model, dtype: object

In [51]:
y_small.value_counts()

model
human           50
mistral-chat     6
mpt              6
mpt-chat         6
llama-chat       6
mistral          6
gpt2             5
gpt4             3
cohere-chat      3
cohere           3
gpt3             3
chatgpt          3
Name: count, dtype: int64

In [64]:
raid_test_100 = pd.concat([X_small, y_small], axis=1)

In [65]:
raid_test_100 = raid_test_100.reset_index().drop("index", axis=1)

In [66]:
raid_test_100.head(10)

,generation,attack,domain,repetition_penalty,model
0,Segmentations-Leak: Membership Inference Attac...,perplexity_misspelling,abstracts,no,mistral-chat
1,"Farshid Jamshidian is a finance researcher, ac...",insert_paragraphs,wiki,NaN,human
2,Transient spine enlargement (3-5 min timesca...,alternative_spelling,abstracts,NaN,human
3,The viola da Terceira (also viola Terceiren...,whitespace,wiki,NaN,human
4,Yes this review is 2 years after the film's re...,insert_paragraphs,reviews,NaN,human
5,Tony Blair is to launch a new campaign to wi...,whitespace,news,no,mpt
6,In an underground world where technology reign...,perplexity_misspelling,books,yes,mpt-chat
7,"2 cloves garlic, peeled\n5 grams garlic oil\n1...",synonym,recipes,NaN,human
8,Men said at vespers: 'All is well!'\nIn one wi...,alternative_spelling,poetry,NaN,human
9,"In the realm of verse, a new wave emerges,\nA ...",number,poetry,no,llama-chat

In [74]:
raid_test_100.value_counts(['model'])

model
human           50
llama-chat       6
mistral          6
mistral-chat     6
mpt              6
mpt-chat         6
gpt2             5
chatgpt          3
cohere           3
cohere-chat      3
gpt3             3
gpt4             3
Name: count, dtype: int64

In [67]:
raid_test_100.to_csv("raid_test_100.csv")